### ISSUE TITLE
Use modal as side panel?

### ISSUE THREAD

**Issue by adambedford** [kaliber5/ember-bootstrap#314]
I'm trying to replicate some functionality in ember that I currently have in my non-ember app whereby I have customized the bootstrap modal to slide in from the right and stay attached to the right, with a height of `100%`, like a side panel.

I'm looking for some guidance on how to reproduce this with ember-bootstrap using Bootstrap v4. I think the difference with Bootstrap 4 is that modals don't have the `in` class applied (?)

Here's the CSS I'm currently using:

```css
.modal.right .modal-dialog {
  position: fixed;
  margin: auto;
  width: 100%;
  height: 100%;
  -webkit-transform: translate3d(0%, 0, 0);
  -ms-transform: translate3d(0%, 0, 0);
  -o-transform: translate3d(0%, 0, 0);
  transform: translate3d(0%, 0, 0);
}

.modal.right.fade .modal-dialog {
  right: -320px;
  -webkit-transition: opacity 0.3s linear, right 0.3s ease-out;
  -moz-transition: opacity 0.3s linear, right 0.3s ease-out;
  -o-transition: opacity 0.3s linear, right 0.3s ease-out;
  transition: opacity 0.3s linear, right 0.3s ease-out;
}

.modal.right.fade.in .modal-dialog {
  right: 0;
}
```

This question may not be within the purview of this library, but any help would be greatly appreciated!
