### ISSUE TITLE
Yield close action from tooltip/popover

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#475]

**Comment by lifeart** [comment]
@simonihmig  my temp solution:
```css
#ember-bootstrap-wormhole {
  .popover-content {
    position: relative;
    float: left;
  }
}
```

```js
//in popover component
export default Component.extend({
  inPopover: false,
  getPopoverParent() {
    return this.parentView.parentView.parent;
  },
  mouseEnter() {
    // popover parent magic, to prevent hiding on active mouse
    if (this.get("inPopover")) {
      this.getPopoverParent().set("hoverState", "in");
    }
  },
  mouseLeave() {
    // popover parent magic, to prevent hiding on active mouse
    if (this.get("inPopover")) {
      this.getPopoverParent().set("hoverState", "out");
      this.getPopoverParent().hide();
    }
  }
});
```
