### ISSUE TITLE
Adding classes to accordian item for spacing

### ISSUE THREAD

**Issue by kennedybaird** [kaliber5/ember-bootstrap#623]
Hi guys,

One common variation on the accordion is applying spacing between the items (using `mb-2` etc)

It would be nice to be able to do this with either:

```handlebars
{{#bs-accordian spaced as |acc|}}
```
or
```handlebars
{{#acc.item class='mb-2' value=1 title='First Item'}}
```
or
```handlebars
{{#bs-accordian spacing=X as |acc|}}
```
where X is 1-5 through bootstraps `mb-X` 

etc. I think I could try making a pull request to add this in if it was desired :), would just need a suggestion on the ideal solution between the options above

Screenshot of normal bootstrap accordian with `mb-2` on each `card` / `acc.item`

![image](https://user-images.githubusercontent.com/20593811/42408186-b26d8c0e-81f2-11e8-8e6f-2758b443a795.png)

**Comment by simonihmig** [comment]
I would prefer your second version, but I wonder, doesn't this already work?

**Comment by Techn1x** [comment]
Seems to work
https://ember-twiddle.com/24f81f26fe7e2daf41d8babfd1e06bc5?openFiles=templates.application.hbs%2C

Only thing I notice is that each accordion item (except for the last one), when opened, doesn't have the bottom border (this could probably be added in CSS)

**Comment by kennedybaird** [comment]
Ah, I didn't try.

The documentation doesn't say class is available for acc.item.

https://www.ember-bootstrap.com/api/classes/Components.AccordionItem.html

Is class available by default for all bs items?

Using the third option would allow for accounting for the extra bottom border. Although that can be fixed via css.

I would love to try making this available, do you think it is worth making a pull request?

**Comment by Techn1x** [comment]
Class works on most bs items/components that I've tried

**Comment by kennedybaird** [comment]
Right, thanks. Couldn't find it saying that anywhere in the docs!

**Comment by simonihmig** [comment]
> Is class available by default for all bs items?

It's a feature of `Ember.Component`, so available for all components (unless they are tagless, i.e. `tagName: ''`)!

**Comment by kennedybaird** [comment]
So, that's cool.

However it still looks very hacked, as the rounded borders etc are not present between the items, can do this with css but would require logic to apply borders differently to first, middle and last items.

**Comment by Techn1x** [comment]
> can do this with css but would require logic to apply borders differently to first, middle and last items.

Nah, since the cards are all separated you can apply the same CSS to all. I updated the ember-twiddle above with some CSS that should work for you.
```css
.accordion.spaced-accordion > .card {
  margin-bottom: 10px;
  border-bottom: 1px solid #DFDFDF !important;
  border-radius: 0.25rem !important;
}

.accordion.spaced-accordion > .card > .card-header {
  border-bottom: 0;
}

.accordion.spaced-accordion > .card .card-body {
  border-top: 1px solid #DFDFDF;
}
```
